### ISSUE TITLE
GlobalStateService and Reward stale APIs

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/api#163]
The implementation of a few API endpoints and the `Reward` message type has been changed:
https://github.com/spacemeshos/go-spacemesh/commit/697addae233e114e968d9c82348aad54dd873779

So this repo needs an update to represent an actual API:
- `GlobalStateService.SmesherRewardStream` and `GlobalStateService.SmesherDataQuery` are deprecated: they throws an exception "UNIMPLEMENTED DEPRECATED". So let's remove them from proto files.
- `Reward` type (that returned within `GlobalStateService.AccountDataQuery/Stream` endpoints) has no more `SmesherID` field

Changes not released within `v0.2.16-beta.0` are out of scope.

@countvonzero am I missing something else?

**Comment by lrettig** [comment]
As discussed in the linked issue/go-spacemesh repo discussion, these changes are not urgent, but it would be good to add new endpoint(s) to stream and/or query rewards from a given smesher, since the node does have this data (but it's not persisted to the mesh, not part of the protocol, and it's ephemeral since it lives in proposals and cannot be reconstructed).
