### ISSUE TITLE
Fully parsed tx types

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#288]
Right now the API only returns parsed "raw" transactions that include the principal, template, and method selector but not the method payload nor the parsed payload (which for a 'Send' tx would include recipient and amount):

https://github.com/spacemeshos/api/blob/eebe59f68193f37ddd8af35a929ac12ef31ec857/spacemesh/v1/types.proto#L45-L58

This makes reading tx data unnecessarily difficult for clients. Add one or more fully-parsed tx types (for spawn, send, etc.).

**Comment by Avionic23** [comment]
Hi, @lrettig. I've been trying to decode the raw transaction with 'go-scale' library into different data structures like Spend, SpendBody, SpendPayload, SpendArguments. Unfortunately , none of those has worked. I'm kindly asking if it's possible to decode address of the receiver from raw transaction. Also, I'd like to know what fields are included in the raw transaction and in which order because I've found several sources with different data structures and I'm not sure which one is correct. Thanks

**Comment by lrettig** [comment]
This is being handled in APIv2 now in #319; see the work in progress here: https://github.com/spacemeshos/api/pull/319/files#diff-8ebf744ee0115b17bf0e41111f7f3d9ea7c8b4205532e81f9a3e287e5c3154b9.

@Avionic23 please see https://github.com/spacemeshos/wiki/wiki/Integration-guide#transactions. The authoritative code you're looking for lives in https://github.com/spacemeshos/go-spacemesh/blob/develop/genvm/vm.go. It's definitely possible to parse a raw tx into a tx type and to parse the arguments as you describe; go-spacemesh does exactly this. We don't yet have a clean SDK that makes doing this easy but hopefully we will soon. Let me know if you still have questions.

**Comment by Avionic23** [comment]
Hey, @lrettig. Thank you for you help. I reviewed  https://github.com/spacemeshos/go-spacemesh/blob/develop/genvm/vm.go and noticed that the addresses are actually 24 bytes long, but in go-scale they are still 20 bytes long. I assume that's the reason because after replacing [20]byte address to types.Address (which is underlying [24]byte data type) the the receiver and amount arguments were successfully parsed.
