### ISSUE TITLE
What should streams return?

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#5]
I proposed that streams return "events" along with an "event type" - e.g., for Account, the "event type" would be something like BALANCE_UPDATED or NONCE_UPDATED.

@avive proposed that the stream just stream updated Account objects.

In the former case, you can figure out what happened just by looking at the stream, i.e., statelessly. In the latter case you'd need to compare to previous state.

I'm not sure if this matters.

See https://github.com/spacemeshos/api/pull/2#discussion_r417531729.

**Comment by avive** [comment]
It does matter. I think we should not return events at all - just data objects that includes the current state from the mesh perspective on a node - see my comments in the PR review.

**Comment by avive** [comment]
So, in this design pattern, when data changes which would have triggered an event stream call - that data object is just sent as-is on its standard stream instead of raising the event so the client gets it from that data object. e.g. a transaction status field. We have to deal with the same objects changing states anyhow as layers, blocks, transactions are all not really immutable and can change state in several cases. e.g. tortoise overrides hare results, self healing, state transition function output etc... if we just stick with objects then we have a forward-compatible design with reorgs which is super important for this project...

**Comment by lrettig** [comment]
Discussed with Aviv, we're both comfortable with his proposal that the API just stream data elements as they change, not events. Per @avive:

> I think it is good we keep the node data api as low-level and stateless as possible with just emitting data as it is created or updated and let modules up in the flow deal with what state they are interested at and track this

We're not concerned about consuming more bandwidth for small changes in state since these nodes will probably be running local to the consumer anyway. Basically we'll just "keep the streams dumb."

**Comment by lrettig** [comment]
Cf. Aviv's helpful comments here: https://github.com/spacemeshos/api/pull/2#discussion_r417802062
